// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-episodes.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
import { series } from "npm:@/data/episodes";
var list_episodes_default = defineTool({
  name: "list_episodes",
  title: "List episodes",
  description: "List every episode of the Chrono Chills series STILL HERE, including number, title, subtitle, duration, and premium-lock status.",
  inputSchema: {
    premiumOnly: z.boolean().optional().describe("If true, return only premium-locked episodes."),
    freeOnly: z.boolean().optional().describe("If true, return only free (non-locked) episodes.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ premiumOnly, freeOnly }) => {
    let episodes = series.episodes;
    if (premiumOnly) episodes = episodes.filter((e) => e.isLocked);
    if (freeOnly) episodes = episodes.filter((e) => !e.isLocked);
    const rows = episodes.map((e) => ({
      id: e.id,
      number: e.number,
      title: e.title,
      subtitle: e.subtitle,
      duration: e.duration,
      isLocked: !!e.isLocked,
      isNew: !!e.isNew,
      url: `https://chronochills.com/watch/${e.id}`
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { series: series.title, count: rows.length, episodes: rows }
    };
  }
});

// src/lib/mcp/tools/get-episode.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
import { series as series2 } from "npm:@/data/episodes";
var get_episode_default = defineTool2({
  name: "get_episode",
  title: "Get episode details",
  description: "Get full details for a single Chrono Chills episode by episode id (e.g. 'ep-12') or by episode number.",
  inputSchema: {
    id: z2.string().optional().describe("Episode id such as 'ep-0' or 'ep-42'."),
    number: z2.number().int().optional().describe("Episode number, e.g. 12.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ id, number }) => {
    if (!id && number === void 0) {
      return {
        content: [{ type: "text", text: "Provide either an episode id or a number." }],
        isError: true
      };
    }
    const ep = series2.episodes.find(
      (e) => (id ? e.id === id : true) && (number !== void 0 ? e.number === number : true)
    );
    if (!ep) {
      return {
        content: [{ type: "text", text: "Episode not found." }],
        isError: true
      };
    }
    const row = {
      id: ep.id,
      number: ep.number,
      title: ep.title,
      subtitle: ep.subtitle,
      duration: ep.duration,
      isLocked: !!ep.isLocked,
      isNew: !!ep.isNew,
      url: `https://chronochills.com/watch/${ep.id}`,
      series: series2.title
    };
    return {
      content: [{ type: "text", text: JSON.stringify(row, null, 2) }],
      structuredContent: row
    };
  }
});

// src/lib/mcp/tools/get-series-info.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { series as series3 } from "npm:@/data/episodes";
var get_series_info_default = defineTool3({
  name: "get_series_info",
  title: "Get series info",
  description: "Return metadata about the Chrono Chills horror series STILL HERE: title, tagline, total episode count, free vs premium counts, and pricing.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const total = series3.episodes.length;
    const free = series3.episodes.filter((e) => !e.isLocked).length;
    const info = {
      id: series3.id,
      title: series3.title,
      tagline: series3.tagline,
      totalEpisodes: total,
      freeEpisodes: free,
      premiumEpisodes: total - free,
      pricing: "$1.99/week for premium episodes, or redeem a legacy code.",
      homepage: "https://chronochills.com"
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "chrono-chills-mcp",
  title: "Chrono Chills MCP",
  version: "0.1.0",
  instructions: "Tools for the Chrono Chills horror short-form streaming app. Use `get_series_info` for series-level metadata, `list_episodes` to browse the STILL HERE episode catalog (with optional free/premium filters), and `get_episode` to look up a single episode by id or number. All data is public \u2014 no authentication required.",
  tools: [list_episodes_default, get_episode_default, get_series_info_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
